#!/bin/sh

case "$2" in
commit|message)
	# It appears git invokes this script for interactive rebase but does
	# not remove commented lines, so just exit if we're not called with the
	# default (comment-containing) template.
	grep -E -q '^#' "$1" || exit 0
	;;
template)
	exit 0
	;;
merge)
	exit 0
	;;
esac

outfile=$(mktemp /tmp/freebsd-git-commit.XXXXXXXX)
exec 3> "$outfile"

awk '1;/^#$/{exit}' "$1" >&3

cat >&3 <<EOF
# <Component>: Subject goes here, max 50 cols  --|
# <then a blank line>
#                                                         72 columns --|
#
# Do not add a "Submitted by:" line.  If someone besides the committer sent in
# the change, the commit author should be set using \`git commit --author\`.
#
# Uncomment and complete these metadata fields, as appropriate:
#
# PR:		<If and which Problem Report is related.>
# Reported by:	<If someone else reported the issue.>
# Reviewed by:	<If someone else reviewed your modification.>
# Tested by:	<If someone else tested the change.>
# Approved by:	<If you needed approval for this commit.>
# Obtained from:	<If the change is from a third party.>
# Fixes:	<Short hash and title line of commit fixed by this change>
# Relnotes:	<Set to 'yes' for mention in release notes.>
# Security:	<Vulnerability reference (one per line) or description.>
# Sponsored by:	The FreeBSD Foundation
# Pull Request:	<https://github.com/freebsd/freebsd-doc/pull/###>
# Differential Revision:	<https://reviews.freebsd.org/D###>
#
# "Pull Request" and "Differential Revision" require the *full* GitHub or
# Phabricator URL.
EOF

awk '/^#$/,EOF' "$1" >&3

exec 3>&-

mv "$outfile" "$1"
