name: Main
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Install Chezmoi from Github repo | ${{ matrix.name }}
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: FreeBSD
            distro: freebsd/FreeBSD-12.3-STABLE
          - name: Alpine
            distro: roboxes/alpine315
#          - name: Ubuntu
#            distro: ubuntu/focal64
#          - name: ArchLinux
#            distro: archlinux/archlinux
#          - name: CentOS7
#            distro: centos/7
#          - name: Debian11
#            distro: debian/bullseye64
#          - name: Fedora35
#            distro: fedora/35-cloud-base
#          - name: RockyLinux8
#            distro: rockylinux/8
    steps:
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ matrix.distro }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ matrix.distro }}
      - name: Install | Test | ${{ matrix.name }}
        uses: 5u623l20/github-actions-vagrantup@main
        with:
          mem: 4096
          box: ${{ matrix.distro }}
          run: |
            cd
            { command -v curl > /dev/null && sh -c "$(curl -fsLS https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v wget > /dev/null && sh -c "$(wget -qO- https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v fetch > /dev/null && sh -c "$(fetch -q -o - https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; }
            chezmoi data
            tree ~/ -a -I '.Azure|.Trash|.aliyun|.android|.azcopy|.azure-devops|.bash_sessions|.cabal|.cargo|.conda|.dotnet|.fastlane|.ghcup|.gradle|.npm|.nvm|.rustup|.sbt|.ssh|.subversion|.vcpkg|.yarn|Desktop|Documents|Downloads|Library|Movies|Music|Pictures|bootstrap|hostedtoolcache|project|runners|target|work|.composer|*ActionsService|.docker|.dotnet|.ghcup|.nvm|.rustup|factory|perflog|warmup'
