---
name: Main
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Install Chezmoi from Github repo | ${{ matrix.name }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: FreeBSD
            distro: freebsd/FreeBSD-13.2-STABLE
          - name: Alpine
            distro: roboxes/alpine317
          - name: MacOS
#         - name: Ubuntu
#            distro: ubuntu/focal64
#          - name: CentOS7
#            distro: centos/7
#          - name: Debian11
#            distro: debian/bullseye64
#          - name: Fedora35
#            distro: fedora/35-cloud-base
#          - name: RockyLinux8
#            distro: rockylinux/8
    steps:
      - name: Install | Test | ${{ matrix.name }}
        if: matrix.name != 'MacOS'
        uses: 5u623l20/github-actions-vagrantup@main
        with:
          mem: 4096
          box: ${{ matrix.distro }}
          run: |
            cd
            { command -v curl > /dev/null && sh -c "$(curl -fsLS https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v wget > /dev/null && sh -c "$(wget -qO- https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v fetch > /dev/null && sh -c "$(fetch -q -o - https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; }
            ./bin/chezmoi data
            find ~/ -type f | grep -E -v '.*ActionsService|.Azure|.Trash|.aliyun|.android|.azcopy|.azure-devops|.bash_sessions|.cabal|.cargo|.composer|.conda|.docker|.dotnet|.factory|.fastlane|.ghcup|.gradle|.npm|.nvm|.rustup|.sbt|.ssh|.subversion|.vcpkg|.yarn|Desktop|Documents|Downloads|Library|Movies|Music|Pictures|bootstrap|hostedtoolcache|perflog|project|runners|target|warmup|work'
      - name: Install | Test | ${{ matrix.name }}
        if: matrix.name == 'MacOS'
        run: |
          cd
          { command -v curl > /dev/null && sh -c "$(curl -fsLS https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v wget > /dev/null && sh -c "$(wget -qO- https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v fetch > /dev/null && sh -c "$(fetch -q -o - https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; }
          ./bin/chezmoi data
          find ~/ -type f | grep -E -v '.*ActionsService|.Azure|.Trash|.aliyun|.android|.azcopy|.azure-devops|.bash_sessions|.cabal|.cargo|.composer|.conda|.docker|.dotnet|.factory|.fastlane|.ghcup|.gradle|.npm|.nvm|.rustup|.sbt|.ssh|.subversion|.vcpkg|.yarn|Desktop|Documents|Downloads|Library|Movies|Music|Pictures|bootstrap|hostedtoolcache|perflog|project|runners|target|warmup|work'
  test:
    runs-on: macos-12
    strategy:
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.0'
          - name: openbsd
            architecture: x86-64
            version: '7.4'

    steps:
      - uses: actions/checkout@v4

      - name: Install | Test | ${{ matrix.os.name }}
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: default
          memory: 5G
          cpu_count: 4
          run: |
            cd
            pwd
            { command -v curl > /dev/null && sudo sh -c "$(curl -fsLS https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v wget > /dev/null && sudo sh -c "$(wget -qO- https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v fetch > /dev/null && sudo sh -c "$(fetch -q -o - https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; }
            ./chezmoi data
            find ~/ -type f | grep -E -v '.*ActionsService|.Azure|.Trash|.aliyun|.android|.azcopy|.azure-devops|.bash_sessions|.cabal|.cargo|.composer|.conda|.docker|.dotnet|.factory|.fastlane|.ghcup|.gradle|.npm|.nvm|.rustup|.sbt|.ssh|.subversion|.vcpkg|.yarn|Desktop|Documents|Downloads|Library|Movies|Music|Pictures|bootstrap|hostedtoolcache|perflog|project|runners|target|warmup|work'
  test1:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg install -y curl
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
