---
name: Main
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-macos:
    name: Install Chezmoi from Github repo | ${{ matrix.description }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macos
            description: MacOS
          - name: freebsd
            description: FreeBSD
            architecture: x86-64
            version: '14.0'
    steps:
      - name: Install | Test | ${{ matrix.name }}
        if: matrix.name != 'macos'
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.name }}
          architecture: ${{ matrix.architecture }}
          version: ${{ matrix.version }}
          shell: default
          memory: 5G
          cpu_count: 4
          run: |
            cd
            { command -v curl > /dev/null && sudo sh -c "$(curl -fsLS https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v wget > /dev/null && sudo sh -c "$(wget -qO- https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v fetch > /dev/null && sudo sh -c "$(fetch -q -o - https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; }
            find ~/ -type f | grep -E -v '.*ActionsService|.Azure|.Trash|.aliyun|.android|.azcopy|.azure-devops|.bash_sessions|.cabal|.cargo|.composer|.conda|.docker|.dotnet|.factory|.fastlane|.ghcup|.gradle|.npm|.nvm|.rustup|.sbt|.ssh|.subversion|.vcpkg|.yarn|Desktop|Documents|Downloads|Library|Movies|Music|Pictures|bootstrap|hostedtoolcache|perflog|project|runners|target|warmup|work'
      - name: Install | Test | ${{ matrix.name }}
        if: matrix.name == 'MacOS'
        run: |
          cd
          { command -v curl > /dev/null && sh -c "$(curl -fsLS https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v wget > /dev/null && sh -c "$(wget -qO- https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v fetch > /dev/null && sh -c "$(fetch -q -o - https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; }
          ./bin/chezmoi data
          find ~/ -type f | grep -E -v '.*ActionsService|.Azure|.Trash|.aliyun|.android|.azcopy|.azure-devops|.bash_sessions|.cabal|.cargo|.composer|.conda|.docker|.dotnet|.factory|.fastlane|.ghcup|.gradle|.npm|.nvm|.rustup|.sbt|.ssh|.subversion|.vcpkg|.yarn|Desktop|Documents|Downloads|Library|Movies|Music|Pictures|bootstrap|hostedtoolcache|perflog|project|runners|target|warmup|work'
  deploy-linux:
    name: Install Chezmoi from Github repo | ${{ matrix.description }}
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - description: Alpine
            image: alpine:latest
#         - name: Ubuntu
#            distro: ubuntu/focal64
#          - name: CentOS7
#            distro: centos/7
#          - name: Debian11
#            distro: debian/bullseye64
#          - name: Fedora35
#            distro: fedora/35-cloud-base
#          - name: RockyLinux8
#            distro: rockylinux/8
    steps:
      - name: Install | Test | ${{ matrix.description }}
        run: |
          cd
          { command -v curl > /dev/null && sudo sh -c "$(curl -fsLS https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v wget > /dev/null && sudo sh -c "$(wget -qO- https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; } || { command -v fetch > /dev/null && sudo sh -c "$(fetch -q -o - https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"; }
          find ~/ -type f | grep -E -v '.*ActionsService|.Azure|.Trash|.aliyun|.android|.azcopy|.azure-devops|.bash_sessions|.cabal|.cargo|.composer|.conda|.docker|.dotnet|.factory|.fastlane|.ghcup|.gradle|.npm|.nvm|.rustup|.sbt|.ssh|.subversion|.vcpkg|.yarn|Desktop|Documents|Downloads|Library|Movies|Music|Pictures|bootstrap|hostedtoolcache|perflog|project|runners|target|warmup|work'
