---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-execute:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu-20.04
            platform: ubuntu-20.04
            vagrant: no
          - name: Monterey
            platform: macos-latest
            vagrant: no
          - name: Alpine-3.15.4
            platform: ubuntu-20.04
            vagrant: no
            container: alpine:3.15.4

    continue-on-error: true
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    container: ${{ matrix.container }}
    steps:
      - name: Update $PATH
        run: echo "$HOME/bin" >> $GITHUB_PATH
      - name: Install and initialize chezmoi [Hosts]
        if: matrix.vagrant == 'no'
        run: |
          cd
          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply $GITHUB_ACTOR
      - name: Install and initialize chezmoi [Docker]
        if: matrix.vagrant == 'no'
        run: |
          cd
          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply $GITHUB_ACTOR
      - name: Execute chezmoi data
        if: matrix.vagrant == 'no'
        run: chezmoi data
      - name: Print directory tree
        if: matrix.vagrant == 'no'
        run: tree ~/ -a -I '.Azure|.Trash|.aliyun|.android|.azcopy|.azure-devops|.bash_sessions|.cabal|.cargo|.conda|.dotnet|.fastlane|.ghcup|.gradle|.npm|.nvm|.rustup|.sbt|.ssh|.subversion|.vcpkg|.yarn|Desktop|Documents|Downloads|Library|Movies|Music|Pictures|bootstrap|hostedtoolcache|project|runners|target|work|.composer|*ActionsService|.docker|.dotnet|.ghcup|.nvm|.rustup|factory|perflog|warmup'
