---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-execute:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu-20.04
            platform: ubuntu-20.04
            vagrant: no
            fetchbin: "curl -fsLS "
          - name: Alpine-3.15.4
            platform: ubuntu-20.04
            vagrant: no
            container: alpine:3.15.4
            pkgbin: "apk add tree"
            fetchbin: "wget -qO- "
          - name: AmazonLinux-2
            platform: ubuntu-20.04
            vagrant: no
            container: amazonlinux:2
            fetchbin: "curl -fsLS "
          - name: ArchLinux
            platform: ubuntu-20.04
            vagrant: no
            container: archlinux
            fetchbin: "curl -fsLS "
          - name: CentOS7
            platform: ubuntu-20.04
            vagrant: no
            container: centos:7
            fetchbin: "curl -fsLS "
          - name: Debian11
            platform: ubuntu-20.04
            vagrant: no
            container: debian:11
            fetchbin: "curl -fsLS "
          - name: Fedora34
            platform: ubuntu-20.04
            vagrant: no
            container: fedora:34
            fetchbin: "curl -fsLS "
          - name: OpenSuse-Tumbleweed
            platform: ubuntu-20.04
            vagrant: no
            container: opensuse/tumbleweed
            fetchbin: "curl -fsLS "
          - name: RedHat8
            platform: ubuntu-20.04
            vagrant: no
            container: redhat/ubi8-minimal
            fetchbin: "curl -fsLS "
          - name: RockyLinux8
            platform: ubuntu-20.04
            vagrant: no
            container: rockylinux:8
            fetchbin: "curl -fsLS "

    continue-on-error: true
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    container: ${{ matrix.container }}
    steps:
      - name: Update $PATH
        run: echo "$HOME/bin" >> $GITHUB_PATH
      - name: Install additional packages
        if: matrix.pkgbin != ''
        run: ${{ matrix.pkgbin }}
      - name: Install and initialize chezmoi
        if: matrix.vagrant == 'no'
        run: |
          cd
          sh -c "$(${{ matrix.fetchbin }}https://raw.githubusercontent.com/5u623l20/dotfiles/main/install)"
      - name: Execute chezmoi data
        if: matrix.vagrant == 'no'
        run: chezmoi data
      - name: Print directory tree
        if: matrix.vagrant == 'no'
        run: tree ~/ -a -I '.Azure|.Trash|.aliyun|.android|.azcopy|.azure-devops|.bash_sessions|.cabal|.cargo|.conda|.dotnet|.fastlane|.ghcup|.gradle|.npm|.nvm|.rustup|.sbt|.ssh|.subversion|.vcpkg|.yarn|Desktop|Documents|Downloads|Library|Movies|Music|Pictures|bootstrap|hostedtoolcache|project|runners|target|work|.composer|*ActionsService|.docker|.dotnet|.ghcup|.nvm|.rustup|factory|perflog|warmup'
